#Rodar a aplicação executar no terminal docker compose up -d
#Parar o container docker compose stop
version: '3'
services:
  domainbank:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
