service: feed

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: 'Allow'
      Action: [
         'sqs:SendMessage',
         'sqs:GetQueueUrl',
         "s3:Get*",
         "s3:List*",
      ]
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'sqs:ListQueues'
      Resource: '*'

functions:
  getFeed:
    handler: handler.getFeed
    events:
      - http:
          path: feed
          method: get
          cors: true
      